ORDER_QUERY = "\n  query Orders(\n    $storeIds: [UUID]!\n    $from: String!\n    $to: String!\n    $page: Int = 0\n    $size: Int = 10\n    $orderId: String\n    $liability: String\n    $cards: [CardFilterInput]\n    $operationMode: [String]\n    $cancelOrigin: [String]\n    $scheduled: Boolean\n    $status: [String]\n    $saleChannel: String\n    $includeStore: Boolean = false\n  ) {\n    orders: listOrders(\n      storeIds: $storeIds\n      from: $from\n      to: $to\n      page: $page\n      size: $size\n      orderId: $orderId\n      liability: $liability\n      cards: $cards\n      operationMode: $operationMode\n      cancelOrigin: $cancelOrigin\n      scheduled: $scheduled\n      status: $status\n      saleChannel: $saleChannel\n    ) {\n      groups {\n        date\n        results\n        totalDayValue\n        orders {\n          createdAt\n          id\n          shortId\n          lastStatus: currentStatus\n          isCancellable\n          saleChannel {\n            key\n            value\n            label\n          }\n          customer {\n            id\n          }\n          additionalInfo {\n            metadata {\n              modificationSource\n              externalOrderId\n              orderId\n              externalOrderIdDescription\n              platform\n            }\n          }\n          partnerOrderId\n          bag {\n            partial\n            discount\n            total\n          }\n          benefits {\n            partner\n            own\n            total\n          }\n          deliveryMethod {\n            total\n            mode {\n              type\n              packaging\n            }\n            location {\n              type\n            }\n            scheduling {\n              type\n              date: to\n              scheduledDate\n              isScheduled\n            }\n          }\n          payments {\n            total\n            methods {\n              id\n              description\n              method\n              brand\n              liabilityDescription\n            }\n          }\n          store @include(if: $includeStore) {\n            uuid: id\n            name\n            address {\n              country\n            }\n          }\n        }\n      }\n      results\n      page\n      hasNext\n    }\n  }\n"

ORDER_INFO_QUERY = "\n  query OrderById($orderId: UUID!) {\n    order: getOrder(id: $orderId) {\n      id\n      createdAt\n      status {\n        metadata\n        status\n        createdAt\n        localDate: createdAt\n      }\n      events {\n        value\n        createdAt\n        metadata\n        localDate: createdAt\n      }\n      customer {\n        id\n        name: firstName\n         totalOrders\n        samsClubAccountStatus {\n          status\n          membershipNumber\n        }\n      }\n      deliveryMethod {\n        mode {\n          type\n        }\n        note\n        total\n        scheduling {\n          type\n          date: to\n          scheduledDate\n          isScheduled\n        }\n      }\n      store {\n        config {\n          deliveryTimeInSeconds\n        }\n      }\n      benefits {\n        details {\n          sponsorshipValues\n          campaign\n          amount\n        }\n        own\n        partner\n        total\n      }\n      payments {\n        total\n        methods {\n          id\n          description\n          method\n          liability\n          type\n          brand\n        }\n      }\n      isCancellable\n      saleChannel {\n        key\n        value\n        label\n      }\n      customBag {\n        partial\n        discount\n        total\n        totalValueCancelledItems\n        items {\n          id\n          quantity\n          name\n          note\n          isCancelled\n          hasCancelledSubItems\n          cancelledMessage\n          subItems {\n            id\n            name\n            quantity\n            effectiveUnitPrice\n            totalEffectiveUnitPrice\n            isCancelled\n            cancelledMessage\n          }\n          originalUnitPrice\n          effectiveUnitPrice\n          totalEffectiveUnitPrice\n          totalDiscount\n        }\n      }\n      patchCommittedEvents {\n        value\n        createdAt\n        metadata {\n          changeLevel\n          cancellationOccurrence {\n            cancelCode\n            consumer {\n              paymentType\n              financialOccurrence\n            }\n            logistic {\n              paymentType\n              financialOccurrence\n            }\n            restaurant {\n              paymentType\n              financialOccurrence\n            }\n          }\n        }\n      }\n      currentStatus\n      shortId\n      extraInfo\n      fees {\n        total\n        values {\n          type\n          title\n          description\n          tooltip\n          amount\n        }\n      }\n      financialOcurrences {\n        amount\n        type\n        description\n        transactionDate\n      }\n    }\n  }\n"

ORDER_URL = "https://portal-api.ifood.com.br/next-web-bff/orders/graphql"

ORDER_INFO_URL = "https://portal-api.ifood.com.br/next-web-bff/orders/graphql"

HEADER_BASE = {
  'authority': 'portal-api.ifood.com.br',
  'accept': 'application/json, text/plain, */*',
  'accept-language': 'pt-BR,pt;q=0.7',
  'cache-control': 'no-cache',
  'content-type': 'application/json',
  'origin': 'https://portal.ifood.com.br',
  'pragma': 'no-cache',
  'referer': 'https://portal.ifood.com.br/',
  'sec-ch-ua': '"Chromium";v="110", "Not A(Brand";v="24", "Brave";v="110"',
  'sec-ch-ua-mobile': '?0',
  'sec-ch-ua-platform': '"macOS"',
  'sec-fetch-dest': 'empty',
  'sec-fetch-mode': 'cors',
  'sec-fetch-site': 'same-site',
  'sec-gpc': '1',
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36'
}